# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               BISEL
tagline:             Why do I need a tagline?
url:                 http://hwubisel.github.io
description:         'A collection of stuff'
paginate:            5
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              BISEL
  url:               http://hwubisel.github.io
  email:             biselhwu@gmail.com

# Custom vars
version:             2.0.0


